package(default_visibility = ["//visibility:public"])
load("@jsoj_deps//:requirements.bzl", "requirement")

py_library(
  name = "pie-chart",
  srcs = [
    "pie_chart.py",
  ],
  deps = [
    requirement("plotly"),
  ],
)
