from budget.expense import ExpenseType

TYPE_MAP: dict[str, tuple[str, ExpenseType]] = {
    # ATM
    "ATM": ("ATM Withdrawl", ExpenseType.ATM),
    "WITHDRWL": ("ATM Withdrawl", ExpenseType.ATM),

    # BANKING
    "BankAmeriDeals CASHBACK": ("BankAmeriDeals CASHBACK", ExpenseType.BANKING),
    "TRANSFER": ("Transfer from Checking", ExpenseType.BANKING),

    # CAR_INSURANCE
    "AAA ACG": ("AAA Insurance", ExpenseType.CAR_INSURANCE),

    # CAR_MAINTENANCE
    "AUTOZONE": ("AutoZone", ExpenseType.CAR_MAINTENANCE),
    "PROG MARATHON": ("Car Insurance", ExpenseType.CAR_MAINTENANCE),
    "SEC OF STATE": ("Secretary of State", ExpenseType.CAR_MAINTENANCE),
    "U of M Credit Union": ("Car payment", ExpenseType.CAR_MAINTENANCE),
    "VOLKSWAGEN": ("Car Maintenance", ExpenseType.CAR_MAINTENANCE),

    # CC_PAYMENT
    "Bank of America Credit Card Bill Payment": ("Credit Card Payment from checking account", ExpenseType.CC_PAYMENT),
    "BANK OF AMERICA CREDIT CARD Bill Payment": ("Credit Card Payment from checking account", ExpenseType.CC_PAYMENT),
    "INTEREST CHARGED": ("Interest charged", ExpenseType.CC_PAYMENT),
    "Online Banking payment to CRD 1714": ("Credit Card Payment from checking account", ExpenseType.CC_PAYMENT),
    "Online payment from CHK": ("Credit card payment", ExpenseType.CC_PAYMENT),
    "PAYMENT - THANK YOU": ("Credit card payment", ExpenseType.CC_PAYMENT),

    # CHARITY
    "PRCS RAMALLAH": ("Palestine Red Crescent", ExpenseType.CHARITY),
    "Wikimedia": ("Wikipedia Donation", ExpenseType.CHARITY),

    # CHECK
    "BKOFAMERICA MOBILE": ("Check deposit", ExpenseType.CHECK),
    "Online payment from SAV 4915 7270": ("Online payment from SAV 4915", ExpenseType.CHECK),

    # ENTERTAINMENT
    "APPLE.COM/BILL": ("Apple Services", ExpenseType.ENTERTAINMENT),
    "://apple.com": ("Apple Services", ExpenseType.ENTERTAINMENT),
    "AT&T DEVICE/EQUIP SHIP": ("AT&T", ExpenseType.ENTERTAINMENT),
    "BILL'S BEER GARDEN": ("Bill's Beer Garden", ExpenseType.ENTERTAINMENT),
    "BODHI YOGA": ("Yoga Class", ExpenseType.ENTERTAINMENT),
    "BREATHE YOGA": ("Yoga Class", ExpenseType.ENTERTAINMENT),
    "CEDAR POINT": ("Cedar Point", ExpenseType.ENTERTAINMENT),
    "CIRC BAR": ("Circ Bar", ExpenseType.ENTERTAINMENT),
    "CITY OF DETROIT": ("City of Detroit Parking", ExpenseType.ENTERTAINMENT),
    "CLR*CycleBar": ("CycleBar", ExpenseType.ENTERTAINMENT),
    "CRUNCH FIT": ("Crunch Gym Membership", ExpenseType.ENTERTAINMENT),
    "CTLP*LOCK GOLF ACADEMY": ("Lock Golf Academy", ExpenseType.ENTERTAINMENT),
    "DETROIT INSTITUTE": ("Detroit Institute of Arts", ExpenseType.ENTERTAINMENT),
    "DETROIT INSTITUTE OF ARTS": ("Detroit Institute of Arts", ExpenseType.ENTERTAINMENT),
    "E-ZPASS": ("E-Z Pass Payment", ExpenseType.ENTERTAINMENT),
    "EMAGINE NOVI": ("Emagine Theater", ExpenseType.ENTERTAINMENT),
    "FARMINGTON HILLS GOLF CL": ("Farmington Hills Golf Club", ExpenseType.ENTERTAINMENT),
    "FERNDALE T2 METER": ("Parking Meter", ExpenseType.ENTERTAINMENT),
    "FSP*THE WEDDING SHOPPE": ("The Wedding Shoppe", ExpenseType.ENTERTAINMENT),
    "GOLF FARMINGTON": ("Golf Course", ExpenseType.ENTERTAINMENT),
    "LOCK GOLF ACADEMY": ("Golf Lessons", ExpenseType.ENTERTAINMENT),
    "MIREPOIX": ("Cooking School", ExpenseType.ENTERTAINMENT),
    "PAINTING WITH A TWIST": ("Painting with a Twist", ExpenseType.ENTERTAINMENT),
    "PAS*FERNDALE METERS": ("Ferndale Parking", ExpenseType.ENTERTAINMENT),
    "PlayStation Network": ("PlayStation", ExpenseType.ENTERTAINMENT),
    "Puzzle Me This Provincetown": ("Puzzle Me This Provincetown", ExpenseType.ENTERTAINMENT),
    "SQ *THE LOVING TOUCH": ("The Loving Touch (Venue)", ExpenseType.ENTERTAINMENT),
    "TCKTWEB": ("Ticketweb", ExpenseType.ENTERTAINMENT),
    "THE HAWK FARMINGTON": ("The Hawk Farmington Community Center", ExpenseType.ENTERTAINMENT),
    "TM *TICKETMASTER": ("Ticketmaster", ExpenseType.ENTERTAINMENT),
    "VENMO": ("Venmo Banking", ExpenseType.ENTERTAINMENT),
    "Zelle": ("Zelle Banking", ExpenseType.ENTERTAINMENT),

    # FIXED
    "GRG USA LLC": ("GRG USA LLC Fee/Service", ExpenseType.FIXED),
    "Online Banking transfer to CHK 4519": ("Bug Account Transfer", ExpenseType.FIXED),

    # GAS
    "AG TRAVEL PLAZA": ("Travel Plaza", ExpenseType.GAS),
    "AMOCO": ("Amoco", ExpenseType.GAS),
    "BP#": ("BP Gas", ExpenseType.GAS),
    "C/O OXFORD TRUCK STOP": ("Oxford Truck Stop", ExpenseType.GAS),
    "CIRCLE K": ("Circle K", ExpenseType.GAS),
    "CITGO": ("Citgo Gas", ExpenseType.GAS),
    "CITGO 8 MILE": ("Citgo", ExpenseType.GAS),
    "EXXON": ("Exxon", ExpenseType.GAS),
    "FASTRAC": ("Fastrac Gas", ExpenseType.GAS),
    "HENRY GAS": ("Henry Gas & Conv", ExpenseType.GAS),
    "HOLIDAY STATIONS": ("Holiday Station Stores", ExpenseType.GAS),
    "KRIST OIL": ("Krist Oil", ExpenseType.GAS),
    "LOVE'S": ("Love's Travel Stop", ExpenseType.GAS),
    "MARATHON PETRO": ("Marathon", ExpenseType.GAS),
    "PETRO-CANADA": ("Petro-Canada", ExpenseType.GAS),
    "SHEETZ": ("Sheetz", ExpenseType.GAS),
    "SHELL OIL": ("Shell", ExpenseType.GAS),
    "SPEEDWAY": ("Speedway", ExpenseType.GAS),
    "SUNOCO": ("Sunoco Gas", ExpenseType.GAS),
    "VALOT'S CITGO": ("Citgo", ExpenseType.GAS),

    # GIFTS
    "CRAZYDOGTSHIRTS": ("Crazy Dog T Shirts", ExpenseType.GIFTS),
    "JARED-GALLERIA": ("Jared Jewelry", ExpenseType.GIFTS),
    "PERSONALIZATION MALL": ("Personalization Mall", ExpenseType.GIFTS),
    "STRATTON": ("Stratton", ExpenseType.GIFTS),

    # GROCERY
    "365 Market J": ("365 Market", ExpenseType.GROCERY),
    "BEEFJERKYOUTLET": ("Beef Jerky Outlet", ExpenseType.GROCERY),
    "BUSCH'S": ("Busch's Fresh Food Market", ExpenseType.GROCERY),
    "JOE'S PRODUCE": ("Joe's Produce", ExpenseType.GROCERY),
    "KAPOLNEK FARMS": ("Kapolnek Meat Farms", ExpenseType.GROCERY),
    "KROGER": ("Kroger", ExpenseType.GROCERY),
    "MEIJER": ("Meijer", ExpenseType.GROCERY),
    "WEGMANS": ("Wegmans", ExpenseType.GROCERY),
    "ZERBOS MARKET & BISTRO": ("Zerbo's Market", ExpenseType.GROCERY),

    # MEDICAL
    "TWIN OAKS DENTAL": ("Dental Visit", ExpenseType.MEDICAL),
    "WEST OAKLAND OB GYN": ("OBGYN Visit", ExpenseType.MEDICAL),

    # PADDINGTON_FOOD
    "CHEWY.COM": ("Chewy", ExpenseType.PADDINGTON_FOOD),
    "PETSMART": ("PetSmart", ExpenseType.PADDINGTON_FOOD),
    "TOLONEN FAMILY PET SHOP": ("Tolonen Family Pet Shop", ExpenseType.PADDINGTON_FOOD),

    # PADDINGTON_VET
    "ANGEL ANIMAL HOSPITAL": ("Angel Animal Hospital", ExpenseType.PADDINGTON_VET),
    "HEALTHY PAWS PET INSUR": ("Healthy Paws Pet Insurance", ExpenseType.PADDINGTON_VET),

    # PAYROLL
    "FORD MOTOR CO": ("Ford Motor Company Payroll", ExpenseType.PAYROLL),

    # RESTAURANT
    "BASAN DETROIT": ("Basan Detroit", ExpenseType.RESTAURANT),
    "TST*AQUA": ("Aqua Bar Provincetown", ExpenseType.RESTAURANT),
    "BROWNDOG BARLOR": ("Brown Dog Barlor", ExpenseType.RESTAURANT),
    "CHICK FIL A": ("Chick-fil-A", ExpenseType.RESTAURANT),
    "CHICKEN KRAZE": ("Chicken Kraze", ExpenseType.RESTAURANT),
    "CHIPOTLE": ("Chipotle", ExpenseType.RESTAURANT),
    "COLLEGETOWN BAGELS": ("Collegetown Bagels", ExpenseType.RESTAURANT),
    "CP-DONUTS": ("Donut Shop", ExpenseType.RESTAURANT),
    "DILLY'S DELI": ("Dilly's Deli PHX", ExpenseType.RESTAURANT),
    "DISCOUNT DRINKS NORTH": ("Discount Drinks North", ExpenseType.RESTAURANT),
    "DOLCETTO": ("Dolcetto Specialty Foods", ExpenseType.RESTAURANT),
    "DUA VINO": ("Dua Vino", ExpenseType.RESTAURANT),
    "DUNKIN": ("Dunkin Donuts", ExpenseType.RESTAURANT),
    "EARLY BIRD OF NORTHVILLE": ("Early Bird", ExpenseType.RESTAURANT),
    "EH! BURGER": ("Eh! Burger", ExpenseType.RESTAURANT),
    "EL JALAPENO": ("El Jalapeno", ExpenseType.RESTAURANT),
    "EL PATIO MEXICAN RESTAURA": ("El Patio Mexican", ExpenseType.RESTAURANT),
    "FARMINGTON BREWING": ("Farmington Brewing Company", ExpenseType.RESTAURANT),
    "HARVEST CAFE & BAKER": ("Harvest Cafe and Bakery", ExpenseType.RESTAURANT),
    "BEAN AND LEAF": ("Bean and Leaf Cafe", ExpenseType.RESTAURANT),
    "TRURO VINEYARDS": ("Truro Vineyards", ExpenseType.RESTAURANT),
    "J DUSI WINES": ("J Dusi Vineyards", ExpenseType.RESTAURANT),
    "KDUB'S GRILL": ("K-Dub's Grill", ExpenseType.RESTAURANT),
    "LA PECORA NERA": ("La Pecora Nera", ExpenseType.RESTAURANT),
    "MCDONALD'S": ("McDonald's", ExpenseType.RESTAURANT),
    "PARADISE STREET EATS": ("Paradise Street Eats", ExpenseType.RESTAURANT),
    "RAOGARIVINDU": ("Vindu Indian Market", ExpenseType.RESTAURANT),
    "R&B MILLER FARMS": ("R&B MILLER FARMS", ExpenseType.RESTAURANT),
    "SHIRO RESTAURANT": ("Shiro Restaurant", ExpenseType.RESTAURANT),
    "SPO*IMPERIAL": ("Imperial Ferndale", ExpenseType.RESTAURANT),
    "SQ *CHOCOLATE CHIPPED BAK": ("Chocolate Chipped Bakery", ExpenseType.RESTAURANT),
    "SQ *DUKE'S DONUTS": ("Duke's Donuts", ExpenseType.RESTAURANT),
    "STEVER'S CANDIES": ("Stever's Candies", ExpenseType.RESTAURANT),
    "THAI ELEPHANT": ("Thai Elephant", ExpenseType.RESTAURANT),
    "TOMATOESAP*": ("Tomatoes Apizza", ExpenseType.RESTAURANT),
    "TOTAL WINE AND MORE": ("Total Wine", ExpenseType.RESTAURANT),
    "TRATA-THE RESTAURANT": ("Trata Rochester", ExpenseType.RESTAURANT),
    "TRIO EATS": ("Trio Eats", ExpenseType.RESTAURANT),
    "TST* POP'S FOR ITALIAN": ("Pop's For Italian", ExpenseType.RESTAURANT),
    "TST*ACHATZ PIES": ("Achatz Handmade Pies", ExpenseType.RESTAURANT),
    "TST*BULLDOGS": ("Bulldogs Cheesesteaks", ExpenseType.RESTAURANT),
    "TST*CEDARLAND RESTAURANT": ("Cedarland Restaurant", ExpenseType.RESTAURANT),
    "TST*EARLY BIRD OF NORTHV": ("Early Bird Northville", ExpenseType.RESTAURANT),
    "TST* FIXINS SOUL KITCHEN": ("Fixins Soul Kitchen", ExpenseType.RESTAURANT),
    "UBER *EATS": ("Uber Eats", ExpenseType.RESTAURANT),
    "WAFFLE CABIN": ("Waffle Cabin", ExpenseType.RESTAURANT),

    # RESTAURANT_WORK_LUNCH
    "365 MARKET": ("Work Micro-Market", ExpenseType.RESTAURANT_WORK_LUNCH),
    "AMK FORD THE HIVE": ("Ford The Hive", ExpenseType.RESTAURANT_WORK_LUNCH),
    "FORDS GARAGE DEARBORN": ("Ford's Garage Dearborn", ExpenseType.RESTAURANT_WORK_LUNCH),
    "TST*BROME MODERN EATERY": ("Brome Modern Eatery", ExpenseType.RESTAURANT_WORK_LUNCH),
    "TST*OAKWOOD BAR & GRILL": ("Oakwood Bar & Grill", ExpenseType.RESTAURANT_WORK_LUNCH),

    # SAVINGS
    "Online Banking transfer to SAV 4915": ("Savings Account Transfer", ExpenseType.SAVINGS),

    # SHOPPING
    "SALTY VIBES RESORT": ("Salty Vibes Resstort", ExpenseType.SHOPPING),
    "ATLANTIC SPICE COMPAN": ("Atlantic Spice Company", ExpenseType.SHOPPING),
    "ALEXANDER TRUE VALUE": ("True Value Hardware", ExpenseType.SHOPPING),
    "AMAZON": ("Amazon", ExpenseType.SHOPPING),
    "ATSON INC.": ("Atson Inc.", ExpenseType.SHOPPING),
    "BEST BUY": ("Best Buy", ExpenseType.SHOPPING),
    "BESTBUY": ("Best Buy", ExpenseType.SHOPPING),
    "Canva*": ("Canva", ExpenseType.SHOPPING),
    "Crate and Barrel": ("Crate and Barrel", ExpenseType.SHOPPING),
    "CRATE & BARREL": ("Crate & Barrel", ExpenseType.SHOPPING),
    "CVS/PHARMACY": ("CVS Pharmacy", ExpenseType.SHOPPING),
    "Dicks Sporting Goods": ("Dick's Sporting Goods", ExpenseType.SHOPPING),
    "FARMER JOHN'S GREENHOUSE": ("Farmer John's Greenhouse", ExpenseType.SHOPPING),
    "FARMINGTON CENTER FLORIST": ("Farmington Center Florist", ExpenseType.SHOPPING),
    "GOODWILL IND": ("Goodwill", ExpenseType.SHOPPING),
    "GREAT LAKES ACE HARDWARE": ("Great Lakes Ace Hardware", ExpenseType.SHOPPING),
    "HOMEGOODS": ("HomeGoods", ExpenseType.SHOPPING),
    "INSPIRE MARKETPLACE": ("Inspire Marketplace", ExpenseType.SHOPPING),
    "ISLAND BOOKS & CRAFTS": ("Island Books & Crafts", ExpenseType.SHOPPING),
    "LONDONDERRY VILLAGE": ("Londonderry Village", ExpenseType.SHOPPING),
    "RIVERBEND FARMS": ("Riverbend Farms", ExpenseType.SHOPPING),
    "CLOUDS": ("Clouds", ExpenseType.SHOPPING),
    "MENARDS": ("Menards", ExpenseType.SHOPPING),
    "MICHAELS": ("Michaels", ExpenseType.SHOPPING),
    "PEPPER PALACE": ("Pepper Palace", ExpenseType.SHOPPING),
    "PP*VOGUEBOOGE CANDLES": ("Voguebooge Candles", ExpenseType.SHOPPING),
    "SP THE BOSTON TEA RO": ("The Boston Tea Room", ExpenseType.SHOPPING),
    "SQ *ANGELWORKS JEWELRY": ("Angelworks Jewelry", ExpenseType.SHOPPING),
    "SQ *SPIKEART INC.": ("Spikeart Inc.", ExpenseType.SHOPPING),
    "SUR LA TABLE": ("Sur La Table", ExpenseType.SHOPPING),
    "Swarovski": ("Swarovski", ExpenseType.SHOPPING),
    "TARGET": ("Target", ExpenseType.SHOPPING),
    "THE HOME DEPOT": ("Home Depot", ExpenseType.SHOPPING),
    "THE UPS STORE": ("The UPS Store", ExpenseType.SHOPPING),
    "TJMAXX": ("TJ Maxx", ExpenseType.SHOPPING),
    "USPS KIOSK": ("Post Office", ExpenseType.SHOPPING),
    "WAL-MART": ("Walmart", ExpenseType.SHOPPING),
    "WALGREENS": ("Walgreens", ExpenseType.SHOPPING),
    "WALMART": ("Walmart", ExpenseType.SHOPPING),
    "WILLIAMS-SONOMA": ("Williams Sonoma", ExpenseType.SHOPPING),
    "ZINNIA JEWELRY": ("Zinnia Jewelry", ExpenseType.SHOPPING),

    # SHOPPING_CLOTHES
    "AZAZIE INC": ("Azazie", ExpenseType.SHOPPING_CLOTHES),
    "COTTON ON": ("Cotton On", ExpenseType.SHOPPING_CLOTHES),
    "DSW": ("DSW", ExpenseType.SHOPPING_CLOTHES),
    "FRUGAL FANNIES": ("Frugal Fannies", ExpenseType.SHOPPING_CLOTHES),
    "J. CREW": ("J. Crew", ExpenseType.SHOPPING_CLOTHES),
    "KOHL'S": ("Kohl's", ExpenseType.SHOPPING_CLOTHES),
    "LEVI'S": ("Levi's", ExpenseType.SHOPPING_CLOTHES),
    "LOFT": ("LOFT", ExpenseType.SHOPPING_CLOTHES),
    "LS APRICOT LANE BOUTI": ("Apricot Lane Boutique", ExpenseType.SHOPPING_CLOTHES),
    "LULULEMON": ("Lululemon", ExpenseType.SHOPPING_CLOTHES),
    "LULUS FASHION LOUNGE": ("Lulus", ExpenseType.SHOPPING_CLOTHES),
    "MACYS": ("Macy's", ExpenseType.SHOPPING_CLOTHES),
    "MUTTY PRINTS": ("Mutty Prints Clothes", ExpenseType.SHOPPING_CLOTHES),
    "NORDSTROM": ("Nordstrom", ExpenseType.SHOPPING_CLOTHES),
    "OLD NAVY": ("Old Navy", ExpenseType.SHOPPING_CLOTHES),
    "PLATOS CLOSET": ("Plato's Closet", ExpenseType.SHOPPING_CLOTHES),
    "SP MESHKI U.S.": ("Meshki", ExpenseType.SHOPPING_CLOTHES),
    "SP MLOUYE INC.": ("Mlouye", ExpenseType.SHOPPING_CLOTHES),
    "SP RETROFETE": ("Retrofete", ExpenseType.SHOPPING_CLOTHES),
    "STRATTON CLOTHING": ("Stratton Clothing", ExpenseType.SHOPPING_CLOTHES),
    "VICTORIA'S SECRET": ("Victoria's Secret", ExpenseType.SHOPPING_CLOTHES),

    # SHOPPING_MAKEUP
    "Alfieri Hair Craft": ("Alfieri Hair Craft", ExpenseType.SHOPPING_MAKEUP),
    "MICHIGANAVETATT&PIERCING": ("Michigan Ave Tattoo", ExpenseType.SHOPPING_MAKEUP),
    "SEPHORA": ("Sephora", ExpenseType.SHOPPING_MAKEUP),
    "SP CAKES BODY": ("Cakes Body", ExpenseType.SHOPPING_MAKEUP),
    "SP OLAPLEX": ("Olaplex", ExpenseType.SHOPPING_MAKEUP),
    "ULTA #": ("Ulta Beauty", ExpenseType.SHOPPING_MAKEUP),
    "VIP NAILS & SPA": ("VIP Nails & Spa", ExpenseType.SHOPPING_MAKEUP),

    # TAXES
    "FREETAXUSA.COM": ("FreeTaxUSA", ExpenseType.TAXES),
    "IRS": ("IRS Tax Payment", ExpenseType.TAXES),
    "USATAXPYMT": ("FreeTaxUSA", ExpenseType.TAXES),

    # TRAVEL
    "AIRBNB": ("Airbnb", ExpenseType.TRAVEL),
    "AMBASSADOR BRIDGE": ("Ambassador Bridge Toll", ExpenseType.TRAVEL),
    "AMERICAN AIR": ("American Airlines", ExpenseType.TRAVEL),
    "BLUE WATER BRIDGE": ("Blue Water Bridge Toll", ExpenseType.TRAVEL),
    "BUTTERFLY EMPORIUM": ("Butterfly Emporium Gatlinburg", ExpenseType.TRAVEL),
    "CLEARME.COM": ("CLEAR Airport Security", ExpenseType.TRAVEL),
    "DELTA AIR": ("Delta Airlines", ExpenseType.TRAVEL),
    "DETROIT AIPORT": ("Detroit Airport Parking/Fees", ExpenseType.TRAVEL),
    "DTW/SAN RNDTRP": ("Flight DTW/SAN", ExpenseType.TRAVEL),
    "MACKINAC BRIDGE": ("Mackinac Bridge Toll", ExpenseType.TRAVEL),
    "MCM GATLINBURG ALDEANS": ("Aldeans Gatlinburg", ExpenseType.TRAVEL),
    "SMITH & SON CORNER KITCH": ("Smith & Son Corner Kitchen TN", ExpenseType.TRAVEL),
    "SQ *DK 4 LLC": ("DK 4 LLC Gatlinburg", ExpenseType.TRAVEL),
    "WWG CONCESSIONS": ("WWG Concessions Gatlinburg", ExpenseType.TRAVEL),
    "COLONY MARKET Atascadero": ("Colony Market Atascadero", ExpenseType.TRAVEL),
    "EVIE MINTEY ATASCADERO": ("Evie Mintey Atascadero", ExpenseType.TRAVEL),
    "PORT SAN LUIS HARBOR": ("PORT SAN LUIS HARBOR", ExpenseType.TRAVEL),
}
