from budget.expense import ExpenseType

TYPE_MAP: dict[str, tuple[str, ExpenseType]] = {
    # Payments / Fees
    "Online payment from CHK": ("Credit card payment", ExpenseType.CC_PAYMENT),
    "PAYMENT - THANK YOU": ("Credit card payment", ExpenseType.CC_PAYMENT),
    "INTEREST CHARGED": ("Interest charged", ExpenseType.FIXED),
    "GRG USA LLC": ("GRG USA LLC Fee/Service", ExpenseType.FIXED),

    # Entertainment / Events / Travel
    "TM *TICKETMASTER": ("Ticketmaster", ExpenseType.ENTERTAINMENT),
    "FSP*THE WEDDING SHOPPE": ("The Wedding Shoppe", ExpenseType.ENTERTAINMENT),
    "FARMINGTON HILLS GOLF CL": ("Farmington Hills Golf Club", ExpenseType.ENTERTAINMENT),
    "CTLP*LOCK GOLF ACADEMY": ("Lock Golf Academy", ExpenseType.ENTERTAINMENT),
    "SQ *THE LOVING TOUCH": ("The Loving Touch (Venue)", ExpenseType.ENTERTAINMENT),
    "MCM GATLINBURG ALDEANS": ("Aldeans Gatlinburg", ExpenseType.TRAVEL),
    "SQ *DK 4 LLC": ("DK 4 LLC Gatlinburg", ExpenseType.TRAVEL),
    "WWG CONCESSIONS": ("WWG Concessions Gatlinburg", ExpenseType.TRAVEL),
    "BUTTERFLY EMPORIUM": ("Butterfly Emporium Gatlinburg", ExpenseType.TRAVEL),
    "SMITH & SON CORNER KITCH": ("Smith & Son Corner Kitchen TN", ExpenseType.TRAVEL),
    "DELTA AIR": ("Delta Airlines", ExpenseType.TRAVEL),
    "DTW/SAN RNDTRP": ("Flight DTW/SAN", ExpenseType.TRAVEL),
    "AMBASSADOR BRIDGE": ("Ambassador Bridge Toll", ExpenseType.TRAVEL),
    "BLUE WATER BRIDGE": ("Blue Water Bridge Toll", ExpenseType.TRAVEL),

    # Pets
    "HEALTHY PAWS PET INSUR": ("Healthy Paws Pet Insurance", ExpenseType.PADDINGTON_VET),
    "TOLONEN FAMILY PET SHOP": ("Tolonen Family Pet Shop", ExpenseType.PADDINGTON_FOOD),
    "CHEWY.COM": ("Chewy", ExpenseType.PADDINGTON_FOOD),
    "PETSMART": ("PetSmart", ExpenseType.PADDINGTON_FOOD),

    # Grocery
    "KROGER": ("Kroger", ExpenseType.GROCERY),
    "MEIJER": ("Meijer", ExpenseType.GROCERY),
    "BUSCH'S": ("Busch's Fresh Food Market", ExpenseType.GROCERY),
    "WEGMANS": ("Wegmans", ExpenseType.GROCERY),
    "ZERBOS MARKET & BISTRO": ("Zerbo's Market", ExpenseType.GROCERY),
    "RAOGARIVINDU": ("Vindu Indian Market", ExpenseType.GROCERY),
    "365 Market J": ("365 Market", ExpenseType.GROCERY),

    # Gas / Auto
    "SPEEDWAY": ("Speedway", ExpenseType.GAS),
    "EXXON": ("Exxon", ExpenseType.GAS),
    "MARATHON PETRO": ("Marathon", ExpenseType.GAS),
    "SHELL OIL": ("Shell", ExpenseType.GAS),
    "VALOT'S CITGO": ("Citgo", ExpenseType.GAS),
    "HOLIDAY STATIONS": ("Holiday Station Stores", ExpenseType.GAS),
    "AMOCO": ("Amoco", ExpenseType.GAS),
    "CITGO 8 MILE": ("Citgo", ExpenseType.GAS),
    "PETRO-CANADA": ("Petro-Canada", ExpenseType.GAS),
    "SHEETZ": ("Sheetz", ExpenseType.GAS),
    "C/O OXFORD TRUCK STOP": ("Oxford Truck Stop", ExpenseType.GAS),
    "AUTOZONE": ("AutoZone", ExpenseType.CAR_MAINTENANCE),

    # Restaurants / Food
    "AMK FORD THE HIVE": ("Ford The Hive", ExpenseType.RESTAURANT_WORK_LUNCH),
    "TST*BULLDOGS": ("Bulldogs Cheesesteaks", ExpenseType.RESTAURANT),
    "DOLCETTO": ("Dolcetto Specialty Foods", ExpenseType.RESTAURANT),
    "FARMINGTON BREWING": ("Farmington Brewing Company", ExpenseType.RESTAURANT),
    "TST*BROME MODERN EATERY": ("Brome Modern Eatery", ExpenseType.RESTAURANT),
    "TST*OAKWOOD BAR & GRILL": ("Oakwood Bar & Grill", ExpenseType.RESTAURANT),
    "TST*ACHATZ PIES": ("Achatz Handmade Pies", ExpenseType.RESTAURANT),
    "DISCOUNT DRINKS NORTH": ("Discount Drinks North", ExpenseType.RESTAURANT),
    "SQ *CHOCOLATE CHIPPED BAK": ("Chocolate Chipped Bakery", ExpenseType.RESTAURANT),
    "FORDS GARAGE DEARBORN": ("Ford's Garage Dearborn", ExpenseType.RESTAURANT),
    "BASAN DETROIT": ("Basan Detroit", ExpenseType.RESTAURANT),
    "TST* POP'S FOR ITALIAN": ("Pop's For Italian", ExpenseType.RESTAURANT),
    "EL PATIO MEXICAN RESTAURA": ("El Patio Mexican", ExpenseType.RESTAURANT),
    "CHICKEN KRAZE": ("Chicken Kraze", ExpenseType.RESTAURANT),
    "TRATA-THE RESTAURANT": ("Trata Rochester", ExpenseType.RESTAURANT),
    "TST* FIXINS SOUL KITCHEN": ("Fixins Soul Kitchen", ExpenseType.RESTAURANT),
    "TST*EARLY BIRD OF NORTHV": ("Early Bird Northville", ExpenseType.RESTAURANT),
    "TOMATOESAP*": ("Tomatoes Apizza", ExpenseType.RESTAURANT),
    "DILLY'S DELI": ("Dilly's Deli PHX", ExpenseType.RESTAURANT),
    "TST*CEDARLAND RESTAURANT": ("Cedarland Restaurant", ExpenseType.RESTAURANT),
    "SPO*IMPERIAL": ("Imperial Ferndale", ExpenseType.RESTAURANT),
    "UBER *EATS": ("Uber Eats", ExpenseType.RESTAURANT),
    "TOTAL WINE AND MORE": ("Total Wine", ExpenseType.RESTAURANT),
    "STEVER'S CANDIES": ("Stever's Candies", ExpenseType.RESTAURANT),
    "SQ *DUKE'S DONUTS": ("Duke's Donuts", ExpenseType.RESTAURANT),

    # Shopping – General
    "TARGET": ("Target", ExpenseType.SHOPPING),
    "AMAZON": ("Amazon", ExpenseType.SHOPPING),
    "HOMEGOODS": ("HomeGoods", ExpenseType.SHOPPING),
    "MICHAELS": ("Michaels", ExpenseType.SHOPPING),
    "ALEXANDER TRUE VALUE": ("True Value Hardware", ExpenseType.SHOPPING),
    "WILLIAMS-SONOMA": ("Williams Sonoma", ExpenseType.SHOPPING),
    "GREAT LAKES ACE HARDWARE": ("Great Lakes Ace Hardware", ExpenseType.SHOPPING),
    "MENARDS WIXOM": ("Menards", ExpenseType.SHOPPING),
    "FARMER JOHN'S GREENHOUSE": ("Farmer John's Greenhouse", ExpenseType.SHOPPING),
    "ISLAND BOOKS & CRAFTS": ("Island Books & Crafts", ExpenseType.SHOPPING),
    "SQ *ANGELWORKS JEWELRY": ("Angelworks Jewelry", ExpenseType.SHOPPING),
    "PP*VOGUEBOOGE CANDLES": ("Voguebooge Candles", ExpenseType.SHOPPING),
    "FARMINGTON CENTER FLORIST": ("Farmington Center Florist", ExpenseType.SHOPPING),
    "SQ *SPIKEART INC.": ("Spikeart Inc.", ExpenseType.SHOPPING),
    "BEST BUY": ("Best Buy", ExpenseType.SHOPPING),
    "ATSON INC.": ("Atson Inc.", ExpenseType.SHOPPING),
    "Swarovski": ("Swarovski", ExpenseType.SHOPPING),
    "GOODWILL IND": ("Goodwill", ExpenseType.SHOPPING),
    "Crate and Barrel": ("Crate and Barrel", ExpenseType.SHOPPING),
    "INSPIRE MARKETPLACE": ("Inspire Marketplace", ExpenseType.SHOPPING),
    "SP MLOUYE INC.": ("Mlouye", ExpenseType.SHOPPING),
    "PERSONALIZATION MALL": ("Personalization Mall", ExpenseType.SHOPPING),
    "Dicks Sporting Goods": ("Dick's Sporting Goods", ExpenseType.SHOPPING),
    "TJMAXX": ("TJ Maxx", ExpenseType.SHOPPING),

    # Shopping – Clothing
    "LULULEMON": ("Lululemon", ExpenseType.SHOPPING_CLOTHES),
    "LOFT": ("LOFT", ExpenseType.SHOPPING_CLOTHES),
    "LEVI'S": ("Levi's", ExpenseType.SHOPPING_CLOTHES),
    "VICTORIA'S SECRET": ("Victoria's Secret", ExpenseType.SHOPPING_CLOTHES),
    "MACYS": ("Macy's", ExpenseType.SHOPPING_CLOTHES),
    "DSW": ("DSW", ExpenseType.SHOPPING_CLOTHES),
    "LS APRICOT LANE BOUTI": ("Apricot Lane Boutique", ExpenseType.SHOPPING_CLOTHES),
    "OLD NAVY": ("Old Navy", ExpenseType.SHOPPING_CLOTHES),
    "PLATOS CLOSET": ("Plato's Closet", ExpenseType.SHOPPING_CLOTHES),
    "KOHL'S": ("Kohl's", ExpenseType.SHOPPING_CLOTHES),
    "NORDSTROM": ("Nordstrom", ExpenseType.SHOPPING_CLOTHES),
    "SP MESHKI U.S.": ("Meshki", ExpenseType.SHOPPING_CLOTHES),
    "LULUS FASHION LOUNGE": ("Lulus", ExpenseType.SHOPPING_CLOTHES),
    "SP RETROFETE": ("Retrofete", ExpenseType.SHOPPING_CLOTHES),

    # Shopping – Makeup / Beauty / Self-Care
    "ULTA #": ("Ulta Beauty", ExpenseType.SHOPPING_MAKEUP),
    "Alfieri Hair Craft": ("Alfieri Hair Craft", ExpenseType.SHOPPING_MAKEUP),
    "VIP NAILS & SPA": ("VIP Nails & Spa", ExpenseType.SHOPPING_MAKEUP),
    "SP OLAPLEX": ("Olaplex", ExpenseType.SHOPPING_MAKEUP),
    "SEPHORA": ("Sephora", ExpenseType.SHOPPING_MAKEUP),
    "SP CAKES BODY": ("Cakes Body", ExpenseType.SHOPPING_MAKEUP),
    "MICHIGANAVETATT&PIERCING": ("Michigan Ave Tattoo", ExpenseType.SHOPPING_MAKEUP),

    # Digital / Subscriptions / Services
    "APPLE.COM/BILL": ("Apple Services", ExpenseType.ENTERTAINMENT),
    "FREETAXUSA.COM": ("FreeTaxUSA", ExpenseType.FIXED),
    "USATAXPYMT": ("FreeTaxUSA", ExpenseType.FIXED),
    "CITY OF DETROIT": ("City of Detroit Parking", ExpenseType.ENTERTAINMENT),
    "AT&T DEVICE/EQUIP SHIP": ("AT&T", ExpenseType.ENTERTAINMENT),
    "THE UPS STORE": ("The UPS Store", ExpenseType.SHOPPING),
    "PAS*FERNDALE METERS": ("Ferndale Parking", ExpenseType.ENTERTAINMENT),
    "Canva*": ("Canva", ExpenseType.SHOPPING),
    "Zelle": ("Zelle Banking", ExpenseType.ENTERTAINMENT),
    "VENMO": ("Venmo Banking", ExpenseType.ENTERTAINMENT),
    "IRS": ("IRS Tax Payment", ExpenseType.FIXED),
    "Online Banking transfer to CHK 4519": ("Bug Account Transfer", ExpenseType.FIXED),
    "Online Banking payment to CRD 1714": ("Credit Card Payment from checking account", ExpenseType.CC_PAYMENT),
    "TRANSFER": ("Transfer from Checking", ExpenseType.CC_PAYMENT),
    "FORD MOTOR CO": ("Ford Motor Company Payroll", ExpenseType.PAYROLL),

    # Fitness
    "CLR*CycleBar": ("CycleBar", ExpenseType.ENTERTAINMENT),
    "CRUNCH FIT": ("Crunch Gym  Membership", ExpenseType.ENTERTAINMENT),
}
