package(default_visibility = ["//visibility:public"])

py_library(
  name = "input-util",
  srcs = [
    "input_util.py",
  ],
  deps = [
    ":logging",
  ],
)

py_library(
  name = "logging",
  srcs = [
    "logging.py",
  ],
)



py_library(
  name = "consts",
  srcs = [
    "consts.py",
  ],
)
